table BaseCompras
	lineageTag: beb72521-fab9-468f-842e-0c3803424186

	column 'Data da Compra'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8dc435dc-ec3d-4823-99dd-9dc89df46420
		summarizeBy: none
		sourceColumn: Data da Compra

		variation Variation
			isDefault
			relationship: 08046ac9-270d-4767-ae56-8ace735e714d
			defaultHierarchy: LocalDateTable_1cc4df3a-0537-489c-b03a-d382f6f09f53.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Produto
		dataType: string
		lineageTag: 7eae8bd4-53f9-49b4-ac61-38ed481f96fe
		summarizeBy: none
		sourceColumn: Produto

		annotation SummarizationSetBy = Automatic

	column 'Preco Original'
		dataType: double
		lineageTag: c338ac13-d3a2-4806-a1ee-83b2ffd91dd6
		summarizeBy: sum
		sourceColumn: Preco Original

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Preco com Desconto'
		dataType: double
		lineageTag: 0fadbc4c-8100-4613-81e4-8d9f73575911
		summarizeBy: sum
		sourceColumn: Preco com Desconto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Fornecedor
		dataType: string
		lineageTag: 96f0029e-2c88-4a72-a822-6b769986c3ea
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column 'Qtd. Comprada'
		dataType: int64
		formatString: 0
		lineageTag: a8abbbf9-16af-4dd7-9e67-5c7bcc7e4df9
		summarizeBy: sum
		sourceColumn: Qtd. Comprada

		annotation SummarizationSetBy = Automatic

	column 'Nome Gerente Completo'
		dataType: string
		lineageTag: 136137c1-890b-4673-90a6-98421e992c4a
		summarizeBy: none
		sourceColumn: Nome Gerente Completo

		annotation SummarizationSetBy = Automatic

	column 'Região Destino'
		dataType: string
		lineageTag: d6730c2a-8e1d-4ce5-aa59-1255d8e76623
		summarizeBy: none
		sourceColumn: Região Destino

		annotation SummarizationSetBy = Automatic

	column 'Total Original'
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 068396c7-7a1c-4768-b5f6-b076ad19521d
		summarizeBy: sum
		sourceColumn: Total Original

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Total com Desconto'
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 1fca809c-48b6-4a3b-8786-8ea08c75cd9f
		summarizeBy: sum
		sourceColumn: Total com Desconto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Desconto
		dataType: double
		lineageTag: 5de02832-b5de-4840-83b9-31e5a8addcc3
		summarizeBy: sum
		sourceColumn: Desconto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Funcionário
		dataType: string
		lineageTag: 5caaaf9f-9bdc-4405-8957-81074130ef14
		summarizeBy: none
		sourceColumn: Funcionário

		annotation SummarizationSetBy = Automatic

	partition BaseCompras = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("D:\Renata\Downloads\Compras.xlsx"), null, true),
				    Planilha1_Sheet = Fonte{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Data da Compra", type date}, {"Produto", type text}, {"Preco Original/Preco com Desconto", type text}, {"Fornecedor", type text}, {"Qtd. Comprada", Int64.Type}, {"Comprador", type text}, {"Nome Gerente", type text}, {"Sobrenome Gerente", type text}, {"Região Destino", type text}, {"Column10", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Column10"}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Colunas Removidas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Colunas Mescladas" = Table.CombineColumns(#"Linhas em Branco Removidas",{"Nome Gerente", "Sobrenome Gerente"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Nome Gerente Completo"),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Colunas Mescladas", "Preco Original/Preco com Desconto", Splitter.SplitTextByDelimiter("/", QuoteStyle.Csv), {"Preco Original/Preco com Desconto.1", "Preco Original/Preco com Desconto.2"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Preco Original/Preco com Desconto.1", type number}, {"Preco Original/Preco com Desconto.2", type number}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado1",{{"Preco Original/Preco com Desconto.1", "Preco Original"}, {"Preco Original/Preco com Desconto.2", "Preco com Desconto"}}),
				    #"Multiplicação Inserida" = Table.AddColumn(#"Colunas Renomeadas", "Multiplicação", each [Preco Original] * [Qtd. Comprada], type number),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Multiplicação Inserida",{{"Multiplicação", "Total Original"}}),
				    #"Multiplicação Inserida1" = Table.AddColumn(#"Colunas Renomeadas2", "Multiplicação", each [Preco com Desconto] * [Qtd. Comprada], type number),
				    #"Colunas Renomeadas3" = Table.RenameColumns(#"Multiplicação Inserida1",{{"Multiplicação", "Total com Desconto"}}),
				    #"Subtração Inserida" = Table.AddColumn(#"Colunas Renomeadas3", "Subtração", each [Total Original] - [Total com Desconto], type number),
				    #"Colunas Renomeadas4" = Table.RenameColumns(#"Subtração Inserida",{{"Subtração", "Desconto"}}),
				    #"Coluna Personalizada Adicionada" = Table.AddColumn(#"Colunas Renomeadas4", "Personalizar", each let splitComprador = Splitter.SplitTextByDelimiter(", ", QuoteStyle.None)([Comprador]) in Text.Combine({splitComprador{1}?, " ", splitComprador{0}?}), type text),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Coluna Personalizada Adicionada",{{"Personalizar", "Funcionário"}}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Colunas Renomeadas1",{"Comprador"})
				in
				    #"Colunas Removidas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

